DEFAULT_INDEX_NAME = "nckc-index"
DEFAULT_SOURCE_PROTOCOL = "file"

S3_PROTOCOL = "s3"
EXAMPLE_S3_ENDPOINT_URL = "https://s3.cloudferro.com"
EXAMPLE_S3_BUCKET = "EODATA"

INDEX_CONFIG_VERSION = 2
INDEX_CONFIG_FILENAME = "nckc-config.json"
