DEFAULT_INDEX_NAME = "nckc-index"

DEFAULT_ENDPOINT_URL = "https://s3.cloudferro.com"

DEFAULT_SOURCE_PATH = "EODATA"
DEFAULT_SOURCE_PROTOCOL = "s3"
DEFAULT_SOURCE_STORAGE_OPTIONS = {"endpoint_url": DEFAULT_ENDPOINT_URL}

INDEX_CONFIG_VERSION = 2
INDEX_CONFIG_FILENAME = "nckc-config.json"

